[net]
    model = "features/alexnet/deploy.prototxt"
    weights = "features/alexnet/bvlc_reference_caffenet.caffemodel"
    input_layers = ["data"]
    output_layers = ["fc8"]
    input_width = 227
    input_height = 227

    [net.input]
        dimensions = [
            "batch",
            "channel",
            "height",
            "width",
        ]
        channel_ordering = [
            "blue"
            "green"
            "red"
        ]

[mean-image]
    width = 256
    height = 256
    path = "features/alexnet/imagenet_mean.binaryproto"
