[net]
    model = "nets/caffe_facenet/facenet_deploy.prototxt"
    weights = "nets/caffe_facenet/facenet_deploy.caffemodel"
    input_layers = ["data"]
    output_layers = ["score_final"]

    [net.input]
        dimensions = [
            "batch",
            "channel",
            "height",
            "width"
        ]
        channel_ordering = [
            "red",
            "green",
            "blue"
        ]

[mean-image]
    [mean-image.colors]
        red = 119.29959869
        green = 110.54627228
        blue = 101.8384321
