[net]
    model = "features/cpm/pose_deploy_copy_4sg_resize.prototxt"
    weights = "features/cpm/pose_iter_70000.caffemodel"
    input_layers = ["image"]
    output_layers = ["Mconv7_stage4"]
    input_height = 368
    preserve_aspect_ratio = true
    pad_mod = 8
    normalize = false

    [net.input]
        dimensions = [
            "batch",
            "channel",
            "height",
            "width"
        ]
        channel_ordering = [
            "blue",
            "green",
            "red"
        ]

[mean-image]
    [mean-image.colors]
        blue = 102.9801
        green = 115.9464
        red = 122.7717
