[net]
    model = "features/fcn8s/deploy.prototxt"
    weights = "features/fcn8s/fcn8s-heavy-pascal.caffemodel"
    source = "https://github.com/shelhamer/fcn.berkeleyvision.org/tree/master/voc-fcn8s"
    input_layer = "data"
    output_layers = ["score"]

    [net.input]
        dimensions = [
            "batch",
            "channel",
            "height",
            "width",
        ]
        channel_ordering = [
            "blue"
            "green"
            "red"
        ]

[mean-image]
    [mean-image.colors]
        blue = 104.00698793
        green = 116.66876762
        red =  122.67891434
