[net]
    model = "features/googlenet/deploy.prototxt"
    weights = "features/googlenet/bvlc_googlenet.caffemodel"
    source = "https://github.com/BVLC/caffe/tree/master/models/bvlc_googlenet"
    input_layers = ["data"]
    output_layers = ["pool5/7x7_s1"]
    input_width = 224
    input_height = 224
    normalize = true

    [net.input]
        dimensions = [
            "batch",
            "channel",
            "height",
            "width",
        ]
        channel_ordering = [
            "blue"
            "green"
            "red"
        ]

[mean-image]
    [mean-image.colors]
        blue = 104.00698793
        green = 116.66876762
        red = 122.67891434
