[net]
    model = "features/mscnn/mscnn_deploy.prototxt"
    weights = "features/mscnn/mscnn_kitti_trainval_2nd_iter_35000.caffemodel"
    input_layer = ["data"]
    output_layers = ["bbox_pred", "cls_pred", "proposals_score"]

    [net.input]
        dimensions = [
            "batch",
            "channel",
            "height",
            "width"
        ]
        channel_ordering = [
            "blue",
            "green",
            "red"
        ]

[mean-image]
    [mean-image.colors]
        blue = 104.0
        green = 117.0
        red = 123.0
