[net]
    model = "features/resnet/ResNet-50-deploy.prototxt"
    weights = "features/resnet/ResNet-50-model.caffemodel"
    source = "https://github.com/KaimingHe/deep-residual-networks"
    input_layer = "data"
    output_layers = ["fc1000"]

    [net.input]
        dimensions = [
            "batch",
            "channel",
            "height",
            "width",
        ]
        channel_ordering = [
            "blue"
            "green"
            "red"
        ]

[mean-image]
    [mean-image.colors]
        blue = 104.00698793
        green = 116.66876762
        red = 122.67891434
