[net]
    model = "features/vgg_face_caffe/VGG_FACE_deploy.prototxt"
    weights = "features/vgg_face_caffe/VGG_FACE.caffemodel"
    input_layers = ["data"]
    output_layers = ["fc8"]

    [net.input]
        dimensions = [
            "batch",
            "channel",
            "height",
            "width",
        ]
        channel_ordering = [
            "blue"
            "green"
            "red"
        ]

[mean-image]
    width = 224
    height = 224

    [mean-image.colors]
        blue = 93.5940
        green = 104.7624
        red = 129.1863
